version: '3.8'

services:
  server:
    build: .
    container_name: photoco_backend
    env_file:
      - ./.env
    environment:
      - DB_HOST=photoco_database
      - DB_NAME=$MONGODB_NAME
      - DB_USER=${MONGODB_USERNAME:-root}
      - DB_PASSWORD=${MONGODB_PASSWORD:-root}
      - DB_PORT=27017
    depends_on:
      - mongodb
    volumes:
      - photocodata:/app

volumes:
  photocodata:
