version: '3.8'

services:
  mongodb: 
    image: mongodb/mongodb-community-server
    container_name: photoco_database
    volumes:
      - photoco-services:/mongodb/data/db
    env_file:
      - ./.env
    ports:
      - ${MONGODB_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_NAME:-photoco}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-root}
    restart: always

  redis:
    image: redis
    container_name: photoco_cache
    env_file:
      - ./.env
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - photoco-services:/redis/data
    restart: always

volumes:
  photoco-services:
    driver: local